const validationButton = document.body.querySelector('#validation-button');
const sequenceInput = document.body.querySelector('#sequence');
const printSequence = document.body.querySelector('#print-sequence');
const algoResults = document.body.querySelector('#algo-results');

validationButton.onclick = applyKMR;

/**
 * Executer plein de fois les algos avec des séquences de grande taille
 *  => faire la moyenne du temps mis
 */

function applyKMR(event) {
    sequence = sequenceInput.value;
    // const sequence = "ATGGCTCGGAAACGCGCGGCCGGCGGGGAGCCGCGGGGACGCGAACTGCGCAGCCAGAAATCCAAGGCCAAGAGCAAGGCCCGGCGTGAGGAGGAGGAGGAGGATGCCTTTGAAGATGAGAAACCCCCAAAGAAGAGCCTTCTCTCCAAAGTTTCACAAGGAAAGAGGAAAAGAGGCTGCAGTCATCCTGGGGGTTCAGCAGATGGTCCAGCAAAAAAGAAAGTGGCCAAGGTGACTGTTAAATCTGAAAACCTCAAGGTTATAAAGGATGAAGCCCTCAGCGATGGGGATGACCTCAGGGACTTTCCAAGTGACCTCAAGAAGGCACACCATCTGAAGAGAGGGGCTACCATGAATGAAGACAGCAATGAAGAAGAGGAAGAAAGTGAAAATGATTGGGAAGAGGTTGAAGAACTTAGTGAGCCTGTGCTGGGTGACGTGAGAGAAAGTACAGCCTTCTCTCGATCTCTTCTGCCTGTGAAGCCAGTGGAGATAGAGATTGAAACGCCAGAGCAGGCGAAGACAAGAGAAAGAAGTGAAAAGATAAAACTGGAGTTTGAGACATATCTTCGGAGGGCGATGAAACGTTTCAATAAAGGGGTCCATGAGGACACACACAAGGTTCACCTTCTCTGCCTGCTAGCAAATGGCTTCTATCGAAATAACATCTGCAGCCAGCCAGATCTGCATGCTATTGGCCTGTCCATCATCCCAGCCCGCTTTACCAGAGTGCTGCCTCGAGATGTGGACACCTACTACCTCTCAAACCTGGTGAAGTGGTTCATTGGAACATTTACAGTTAATGCAGAACTTTCAGCCAGTGAACAAGATAACCTGCAGACTACATTGGAAAGGAGATTTGCTATTTACTCTGCTCGAGATGATGAGGAATTGGTCCATATATTCTTACTGATTCTCCGGGCTCTGCAGCTCTTGACCCGGCTGGTATTGTCTCTACAGCCAATTCCTCTGAAGTCAGCAACAGCAAAGGGAAAGAAACCTTCCAAGGAAAGATTGACTGCGGATCCAGGAGGCTCCTCAGAAACTTCCAAAGACGTGCTCCTGACTGCCTGGGAAAATGAGCAGGCAGTCATTGAAAGGAAGGAGAAGGAGAAAAAGGAGAAGCGGGCTCTAGGGAACTGGAAGTTGCTGGCCAAAGGTCTGCTCATCAGGGAGAGGCTGAAGCGTCGCTACGGGCCCAAGAGTGAGGCAGCAGCTCCCCACACAGATGCAGGAGGTGGACTCTCTTCTGATGAAGAGGAGGGGACCAGCTCTCAAGCAGAAGCGGCCAGGATACTGGCTGCCTCCTGGCCTCAAAACCGAGAAGATGAAGAAAAGCAGAAGCTGAAGGGTGGGCCCAAGAAGACCAAAAGGGAAAAGAAAGCAGCAGCTTCCCACCTGTTCCCATTTGAGAAGCTGTGA";
    const start = performance.now();
    kmr = new KMR(sequence);
    const end = performance.now();
    console.log((end-start)+ " ms d'execution javascript");
    printSequence.innerText = `La sequence que vous avez choisi : ${sequence}`;
    algoResults.innerHTML = kmr.toHTML();
}